language: python
python:
- '3.6'
install:
- pip install -U setuptools>=40.1
- pip install .
script: atlas_validation.py --help
deploy:
  provider: pypi
  user: __token__
  password:
    secure: fjvx4U+t4NDQFcM3x1dgorioC6gsamIicIQtS0F43BgLCSsRJhoqZlXzSM8hTw/EHzFT6mXB2KX3dnqdxJXSNmPDdzBHyW9CnJX6LihdV0TS22SH5GNbNvo0+16Js2RpD4eEql0PAaVe7XMZb9T9Tiw4Hte/y9h+T4kSoYgn2arFvIN2xi4SIC5tGCeKoJtoyX8Aj8LDW9CS3j2+aGsrfq7oaq4LTpPIf+2vrPipiREpjKacKnVFuH7b1pQUVkKSR0RhcDzmap/0UEfnFo5C2CQB60wFxxUCZRchWgxBCuOs7NxgrzuWmcKPQnGacVDFuPKWZ4zXRLBeszNk92XSfH9K+nHxtZ52PaWttNgoSgjlh6VTvPlOE7Hpz/xQ15VQ9fXRXC4W8gjIZmyb8YHC6/a2EhJ4JHHYcTk+ADSW8ZKQqc3pr5d9R0nXL+5PwlwBT4d0SukQUnM7mA3LsLA3NXTG4In4xkMy/nx8Rz1nLbFRzSj/Tm7xFBncyC5k3uOcRiGR9dSVDKqw1sUJodU3rY4b5+5bBeBWix6aJsVd2zpai2Ta+8zLjtRT/FCxmpfWRhm2Hw4RfctdD9rUjfnSlPjQ9hFLHZFTHdovLjlgCYSGVUUA4WKnx+z7LxYV1GG7KVgoVzxxg/QP42xMM9XSey9kkaYt1mpZEsTXKhDPONM=
  skip_cleanup: true
  on:
    tags: true
