language: python
python:
  - '3.6'

install:
  - pip install -U setuptools>=40.1
  - pip install .

script: atlas_validation.py --help

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: lVkEhz/xB5mLVi0BTOmrqzKgVVBFI2kTbd1FXKErQKb8sfPxyGWAU124pRD/s0FnWd0anNrAr58TDXp56vRLsVFLL7+PKS1+3uHB+aYlGoiNc2foVfEU7dfGnXTItXDvdF31WSUeqAd8LWqt7+6MJ+N5O85NcfyD562KhM7dDC2w0sFKqHe2fcxbq+gZeBc6bwVxRZ8641NWeiu2HY60HCzG5jSXSABJe/zOAjoW0Z/r41iKtIwWonr47g3OjlYUNkkisW/xkjx4Jvu8duO3679MYFtARAJSur+KvvZWMPfvMsweeEQeLztfPZ0D7Y+vE9YNtb4B0JuPk62qfk/WTJ9sHIcpAbJRM5oL7Hbd09BIVMHQtNfo5Be9lb7vDqiT85ejTMY0ynnaFKaOWCQTUcnv7HnM9liEemgyKMse+VkZpnQzfOPi5cRknImw8I9XGht1MgNfWX4gHtVpidmMGJVI8UqrhNmzdgp7Ia03QkIDIWz0wGKnk3aVgdH1fiqeu/fDt4v1ZHC13Wh+Jj60YCoxI1tyTNPhjUUiPIQvohS0Mb6LlEA1A+eUaJDhz14zCmVDIqtBaDbYTtigCxDzeSLuWnwyTHvpuuCZ28dElqE0D0pDGIzIjRdXC5l21tNLtuxTZ85UhfqJn6lnABNb02HXGy9Ac4nvuTHPz7GDXEw=
  skip_cleanup: true
  on:
    tags: true
